// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package main

const (
	Version     = "v0.4.1"
	GitCommit   = "cd0e95d"          // the commit JUST BEFORE the release
	VersionDate = "2021-09-25 19:54" // UTC
)
