// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package main

const (
	Version     = "v0.4.0"
	GitCommit   = "3524724"          // the commit JUST BEFORE the release
	VersionDate = "2021-09-25 19:51" // UTC
)
